project_id = "dsxrekabnwvarnroanny"

[functions.list-api]
verify_jwt = false

[functions.list-webhook-in]
verify_jwt = false

[functions.list-form]
verify_jwt = false

[functions.api-ingest]
verify_jwt = false

[functions.api-test]
verify_jwt = false

[functions.scheduled-email-dispatch]
verify_jwt = false

[functions.lead-form-submit]
verify_jwt = false

[functions.lead-webhook-in]
verify_jwt = false


[functions.ghl-reply-webhook]
verify_jwt = false

[functions.team-hub-pin-login]
verify_jwt = false

[functions.ema-gmail-gateway]
verify_jwt = false
