project_id = "tjthjgmqdvmgosbzfrif"

[functions.list-api]
verify_jwt = false

[functions.list-webhook-in]
verify_jwt = false

[functions.list-form]
verify_jwt = false

[functions.api-ingest]
verify_jwt = false

[functions.api-test]
verify_jwt = false

[functions.scheduled-email-dispatch]
verify_jwt = false

