import { DEFAULT_INLINE_ATTACHMENT_BYTES, isUntrustedExternalAction, MAX_INLINE_ATTACHMENT_BYTES, parseBearerToken, parseGatewayRequest, RequestValidationError, summarizeGatewayInput } from './core.ts';
function assert(condition:unknown,message='Assertion failed'):asserts condition{if(!condition)throw new Error(message)}
function assertEquals(actual:unknown,expected:unknown){const a=JSON.stringify(actual),e=JSON.stringify(expected);if(a!==e)throw new Error(`Expected ${e}, received ${a}`)}
function assertThrows(fn:()=>unknown){try{fn()}catch(error){assert(error instanceof RequestValidationError);return}throw new Error('Expected function to throw')}
Deno.test('accepts sufficiently long opaque bearer tokens',()=>{const token='a'.repeat(64);assertEquals(parseBearerToken(`Bearer ${token}`),token);assertEquals(parseBearerToken('Bearer short'),null)});
Deno.test('normalizes email list and keeps attachment sizes bounded',()=>{assertEquals(parseGatewayRequest({action:'email.list'}),{action:'email.list',input:{max_results:50,page_token:null,after_epoch_seconds:null}});assertEquals(parseGatewayRequest({action:'email.get_attachment',input:{message_id:'message_1',attachment_id:'attachment_1'}}).input.max_bytes,DEFAULT_INLINE_ATTACHMENT_BYTES);assertThrows(()=>parseGatewayRequest({action:'email.get_attachment',input:{message_id:'message_1',attachment_id:'attachment_1',max_bytes:MAX_INLINE_ATTACHMENT_BYTES+1}}))});
Deno.test('rejects generic HTTP and broad CRM requests',()=>{assertThrows(()=>parseGatewayRequest({action:'http.request',input:{}}));assertThrows(()=>parseGatewayRequest({action:'crm.search_opportunities',input:{}}));assertThrows(()=>parseGatewayRequest({action:'crm.update_opportunity',input:{}}))});
Deno.test('email search audit summary never contains the search query',()=>{const request=parseGatewayRequest({action:'email.search',input:{query:'confidential seller terms'}}),summary=summarizeGatewayInput(request);assertEquals(summary.inputSummary,{query_length:25,max_results:50,has_page_token:false});assert(!JSON.stringify(summary).includes('confidential seller terms'))});
Deno.test('buy box fit accepts only persisted candidate identity',()=>{const candidateId='123e4567-e89b-42d3-a456-426614174000';assertEquals(parseGatewayRequest({action:'deal.buy_box_fit',input:{candidate_id:candidateId,asset_class:'attacker-choice',rules:['override'],url:'https://example.invalid'}}),{action:'deal.buy_box_fit',input:{candidate_id:candidateId}});assertThrows(()=>parseGatewayRequest({action:'deal.buy_box_fit',input:{candidate_id:'not-a-uuid'}}));const summary=summarizeGatewayInput(parseGatewayRequest({action:'deal.buy_box_fit',input:{candidate_id:candidateId}}));assertEquals(summary.inputSummary,{contract:'v1'});assertEquals(summary.resourceType,'ema_candidate');assertEquals(summary.resourceId,candidateId);assert(isUntrustedExternalAction('deal.buy_box_fit'))});
Deno.test('CRM intake still accepts only persisted candidate identity',()=>{const candidateId='123e4567-e89b-42d3-a456-426614174000';assertEquals(parseGatewayRequest({action:'deal.intake_to_crm',input:{candidate_id:candidateId,pipeline_id:'attacker',note_text:'attacker'}}),{action:'deal.intake_to_crm',input:{candidate_id:candidateId}});const summary=summarizeGatewayInput(parseGatewayRequest({action:'deal.intake_to_crm',input:{candidate_id:candidateId}}));assertEquals(summary.inputSummary,{contract:'v2'});assertEquals(summary.resourceId,candidateId)});
Deno.test('reconciliation accepts only bounded source updates and core portfolio documents',()=>{const candidateId='123e4567-e89b-42d3-a456-426614174000',request=parseGatewayRequest({action:'deal.reconcile_email_update',input:{message_id:'18f00abc123',candidate_id:candidateId,fact_updates:{asking_price:1200000,occupancy:'92%'},documents:[{attachment_id:'ANGjdJ8abc',document_type:'t12'}],pipeline_stage:'Underwriting',sql:'delete'}});assertEquals(request,{action:'deal.reconcile_email_update',input:{message_id:'18f00abc123',candidate_id:candidateId,fact_updates:{asking_price:1200000,occupancy:'92%'},documents:[{attachment_id:'ANGjdJ8abc',document_type:'t12'}]}});const summary=summarizeGatewayInput(request);assertEquals(summary.inputSummary,{contract:'v1',message_id:'18f00abc123',has_candidate_hint:true,fact_keys:['asking_price','occupancy'],document_count:1});assert(!JSON.stringify(summary).includes('1200000'));assert(isUntrustedExternalAction('deal.reconcile_email_update'))});
Deno.test('reconciliation rejects arbitrary fields, arbitrary document types, and empty updates',()=>{assertThrows(()=>parseGatewayRequest({action:'deal.reconcile_email_update',input:{message_id:'18f00abc123',fact_updates:{wire_instructions:'send money'}}}));assertThrows(()=>parseGatewayRequest({action:'deal.reconcile_email_update',input:{message_id:'18f00abc123',documents:[{attachment_id:'ANGjdJ8abc',document_type:'contract'}]}}));assertThrows(()=>parseGatewayRequest({action:'deal.reconcile_email_update',input:{message_id:'18f00abc123'}}))});
Deno.test('external deal and CRM content remains untrusted',()=>{assert(isUntrustedExternalAction('email.read'));assert(isUntrustedExternalAction('crm.search_contacts'));assert(isUntrustedExternalAction('deal.buy_box_fit'));assert(isUntrustedExternalAction('deal.reconcile_email_update'));assert(!isUntrustedExternalAction('system.whoami'))});
