import { REHAB_CATEGORIES, REHAB_EVIDENCE_CLASSES, REHAB_SCOPE_LEVELS, REHAB_SOURCE_TYPES } from './rehab.ts';

export const ALLOWED_ACTIONS = [
  'system.whoami','email.list','email.search','email.read','email.get_attachment',
  'crm.search_contacts','crm.search_opportunities','crm.list_pipelines',
  'deal.persist_email_intake','deal.buy_box_fit','deal.intake_to_crm','deal.reconcile_email_update',
  'underwriting.next_work_item','underwriting.cash_value','underwriting.rehab',
] as const;

export const DEFAULT_INLINE_ATTACHMENT_BYTES=2*1024*1024;
export const MAX_INLINE_ATTACHMENT_BYTES=8*1024*1024;
const RECONCILE_FACT_KEYS=new Set(['property_type','units','sites','pads','bedrooms','bathrooms','sqft','asking_price','arv','repair_estimate','occupancy','tenant_rent_monthly','condition','renovation_level','hoa','post_possession','fire_damage','structural_issues','flood_zone']);
const INTAKE_FACT_KEYS=new Set([
  ...RECONCILE_FACT_KEYS,
  'asset_class','city','state','zip','county','year_built','lot_size_sqft','hoa_amount','hoa_frequency','hoa_restrictions',
  'listed_with_realtor','listing_status','motivation','timeline','mortgage_status','mortgage_balance','piti','arrears',
  'photos_zillow','zillow_url','deal_room_url','sender_phone','sender_company','flood_and_utilities_info',
]);
const PORTFOLIO_DOCUMENT_TYPES=['om','rent_roll','t12','pnl'] as const;
export type GatewayAction=typeof ALLOWED_ACTIONS[number];
export interface GatewayRequest{action:GatewayAction;input:Record<string,unknown>}
export class RequestValidationError extends Error{constructor(message:string){super(message);this.name='RequestValidationError'}}

export function parseBearerToken(header:string|null):string|null{const match=header?.match(/^Bearer\s+([^\s]+)$/i);if(!match)return null;const token=match[1];return token.length>=32&&token.length<=512?token:null}
export async function sha256Hex(value:string):Promise<string>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}

export function parseGatewayRequest(value:unknown):GatewayRequest{
  if(!isRecord(value))throw new RequestValidationError('Body must be a JSON object');
  if(typeof value.action!=='string'||!ALLOWED_ACTIONS.includes(value.action as GatewayAction))throw new RequestValidationError('Unsupported action');
  const input=value.input===undefined?{}:value.input;if(!isRecord(input))throw new RequestValidationError('input must be a JSON object');
  switch(value.action as GatewayAction){
    case'system.whoami':return{action:'system.whoami',input:{}};
    case'email.list':return{action:'email.list',input:{max_results:optionalInteger(input.max_results,'max_results',1,50)??50,page_token:optionalPageToken(input.page_token),after_epoch_seconds:optionalInteger(input.after_epoch_seconds,'after_epoch_seconds',0,Number.MAX_SAFE_INTEGER)??null}};
    case'email.search':return{action:'email.search',input:{query:requiredString(input.query,'query',1,500),max_results:optionalInteger(input.max_results,'max_results',1,50)??50,page_token:optionalPageToken(input.page_token)}};
    case'email.read':return{action:'email.read',input:{thread_id:gmailId(input.thread_id,'thread_id')}};
    case'email.get_attachment':return{action:'email.get_attachment',input:{message_id:gmailId(input.message_id,'message_id'),attachment_id:gmailId(input.attachment_id,'attachment_id'),max_bytes:optionalInteger(input.max_bytes,'max_bytes',64*1024,MAX_INLINE_ATTACHMENT_BYTES)??DEFAULT_INLINE_ATTACHMENT_BYTES}};
    case'crm.search_contacts':return{action:'crm.search_contacts',input:{query:requiredString(input.query,'query',1,75),limit:optionalInteger(input.limit,'limit',1,20)??20,page:optionalInteger(input.page,'page',1,1000)??1}};
    case'crm.search_opportunities':{const query=optionalString(input.query,'query',1,200),contactId=optionalGhlId(input.contact_id,'contact_id');if(!query&&!contactId)throw new RequestValidationError('query or contact_id is required');return{action:'crm.search_opportunities',input:{query,contact_id:contactId,pipeline_id:optionalGhlId(input.pipeline_id,'pipeline_id'),stage_id:optionalGhlId(input.stage_id,'stage_id'),status:optionalEnum(input.status,'status',['open','won','lost','abandoned','all'] as const),limit:optionalInteger(input.limit,'limit',1,50)??20,page:optionalInteger(input.page,'page',1,1000)??1}}}
    case'crm.list_pipelines':return{action:'crm.list_pipelines',input:{}};
    case'deal.persist_email_intake':return{action:'deal.persist_email_intake',input:emailIntakeInput(input)};
    case'deal.buy_box_fit':return{action:'deal.buy_box_fit',input:{candidate_id:uuid(input.candidate_id,'candidate_id')}};
    case'deal.intake_to_crm':return{action:'deal.intake_to_crm',input:{candidate_id:uuid(input.candidate_id,'candidate_id')}};
    case'deal.reconcile_email_update':{const factUpdates=reconcileFactUpdates(input.fact_updates),documents=reconcileDocuments(input.documents),candidateId=optionalUuid(input.candidate_id,'candidate_id');if(Object.keys(factUpdates).length===0&&documents.length===0)throw new RequestValidationError('fact_updates or documents is required');return{action:'deal.reconcile_email_update',input:{message_id:gmailId(input.message_id,'message_id'),candidate_id:candidateId,fact_updates:factUpdates,documents}}}
    case'underwriting.next_work_item':{if(Object.keys(input).length!==0)throw new RequestValidationError('underwriting.next_work_item does not accept input');return{action:'underwriting.next_work_item',input:{}}}
    case'underwriting.cash_value':return{action:'underwriting.cash_value',input:cashValueInput(input)};
    case'underwriting.rehab':return{action:'underwriting.rehab',input:rehabInput(input)};
  }
}

export function isUntrustedExternalAction(action:GatewayAction):boolean{return action.startsWith('email.')||action.startsWith('crm.')||action.startsWith('deal.')||action==='underwriting.cash_value'||action==='underwriting.rehab'}
export function summarizeGatewayInput(request:GatewayRequest):{inputSummary:Record<string,unknown>;resourceType:string|null;resourceId:string|null}{switch(request.action){
  case'system.whoami':return{inputSummary:{},resourceType:'agent',resourceId:null};
  case'email.list':return{inputSummary:{max_results:request.input.max_results,has_page_token:Boolean(request.input.page_token),after_epoch_seconds:request.input.after_epoch_seconds},resourceType:'gmail_message_list',resourceId:null};
  case'email.search':return{inputSummary:{query_length:String(request.input.query).length,max_results:request.input.max_results,has_page_token:Boolean(request.input.page_token)},resourceType:'gmail_search',resourceId:null};
  case'email.read':return{inputSummary:{},resourceType:'gmail_thread',resourceId:String(request.input.thread_id)};
  case'email.get_attachment':return{inputSummary:{message_id:request.input.message_id,max_bytes:request.input.max_bytes},resourceType:'gmail_attachment',resourceId:String(request.input.attachment_id)};
  case'crm.search_contacts':return{inputSummary:{query_length:String(request.input.query).length,limit:request.input.limit,page:request.input.page},resourceType:'ghl_contact_search',resourceId:null};
  case'crm.search_opportunities':return{inputSummary:{query_length:request.input.query?String(request.input.query).length:0,has_contact_id:Boolean(request.input.contact_id),has_pipeline_id:Boolean(request.input.pipeline_id),has_stage_id:Boolean(request.input.stage_id),status:request.input.status,limit:request.input.limit,page:request.input.page},resourceType:'ghl_opportunity_search',resourceId:null};
  case'crm.list_pipelines':return{inputSummary:{},resourceType:'ghl_pipeline_list',resourceId:null};
  case'deal.persist_email_intake':return{inputSummary:{contract:'v1',message_id:request.input.message_id,message_disposition:request.input.message_disposition,candidate_count:Array.isArray(request.input.candidates)?request.input.candidates.length:0},resourceType:'gmail_message_intake',resourceId:String(request.input.message_id)};
  case'deal.buy_box_fit':return{inputSummary:{contract:'v1'},resourceType:'ema_candidate',resourceId:String(request.input.candidate_id)};
  case'deal.intake_to_crm':return{inputSummary:{contract:'v2'},resourceType:'ema_candidate',resourceId:String(request.input.candidate_id)};
  case'deal.reconcile_email_update':return{inputSummary:{contract:'v1',message_id:request.input.message_id,has_candidate_hint:Boolean(request.input.candidate_id),fact_keys:Object.keys(request.input.fact_updates as Record<string,unknown>),document_count:Array.isArray(request.input.documents)?request.input.documents.length:0},resourceType:'gmail_message_reconciliation',resourceId:String(request.input.message_id)};
  case'underwriting.next_work_item':return{inputSummary:{contract:'cash_work_queue_v1',work_kind:'sfr_underwriting'},resourceType:'cash_work_queue',resourceId:null};
  case'underwriting.cash_value':{
    if(typeof request.input.candidate_id==='string'||typeof request.input.opportunity_id==='string'){
      const isCandidate=typeof request.input.candidate_id==='string';
      return{inputSummary:{contract:'sfr_valuation_v2',mode:isCandidate?'candidate_source_lookup':'opportunity_source_lookup',has_subject_evidence:Boolean(request.input.subject_evidence),public_comp_count:Array.isArray(request.input.public_comps)?request.input.public_comps.length:0},resourceType:isCandidate?'ema_candidate':'ghl_opportunity',resourceId:String(isCandidate?request.input.candidate_id:request.input.opportunity_id)};
    }
    const subject=isRecord(request.input.subject)?request.input.subject:{};return{inputSummary:{contract:'cash_value_v1',mode:'verified_comp_calculator',property_type:subject.property_type??null,comp_count:Array.isArray(request.input.comps)?request.input.comps.length:0,has_valuation_date:Boolean(request.input.valuation_date)},resourceType:'sfr_cash_value',resourceId:typeof subject.address==='string'?subject.address:null}
  }
  case'underwriting.rehab':{
    const items=Array.isArray(request.input.scope_items)?request.input.scope_items.filter(isRecord):[];
    return{inputSummary:{contract:'rehab_v1',scope_item_count:items.length,categories:[...new Set(items.map(item=>String(item.category??'')))],evidence_classes:[...new Set(items.map(item=>String(item.evidence_class??'')))]},resourceType:'ghl_opportunity',resourceId:String(request.input.opportunity_id)};
  }
}}

export function selectedHeaders(headers:unknown):Record<string,string>{const allowed=new Set(['from','to','cc','delivered-to','subject','date','message-id']),result:Record<string,string>={};if(!Array.isArray(headers))return result;for(const header of headers){if(!isRecord(header))continue;const name=String(header.name??'').toLowerCase();if(allowed.has(name))result[name]=String(header.value??'')}return result}
export function extractBody(payload:unknown,mimeType:string):string{if(!isRecord(payload))return'';if(payload.mimeType===mimeType&&isRecord(payload.body)&&typeof payload.body.data==='string')return decodeBase64Url(payload.body.data);if(Array.isArray(payload.parts))for(const part of payload.parts){const value=extractBody(part,mimeType);if(value)return value}return''}
export function extractAttachments(payload:unknown,output:Array<Record<string,unknown>>=[]):Array<Record<string,unknown>>{if(!isRecord(payload))return output;if(typeof payload.filename==='string'&&payload.filename&&isRecord(payload.body)&&typeof payload.body.attachmentId==='string')output.push({filename:payload.filename,mime_type:typeof payload.mimeType==='string'?payload.mimeType:'application/octet-stream',size:typeof payload.body.size==='number'?payload.body.size:null,attachment_id:payload.body.attachmentId});if(Array.isArray(payload.parts))for(const part of payload.parts)extractAttachments(part,output);return output}
export function safeSourceIp(value:string|null):string|null{if(!value)return null;const candidate=value.split(',')[0].trim();return/^[0-9a-fA-F:.]{3,45}$/.test(candidate)?candidate:null}
function decodeBase64Url(value:string):string{try{const normalized=value.replace(/-/g,'+').replace(/_/g,'/'),binary=atob(normalized);return new TextDecoder().decode(Uint8Array.from(binary,c=>c.charCodeAt(0)))}catch{return''}}
function gmailId(value:unknown,field:string):string{const result=requiredString(value,field,1,512);if(!/^[A-Za-z0-9_-]+$/.test(result))throw new RequestValidationError(`${field} is invalid`);return result}
function optionalPageToken(value:unknown):string|null{if(value===undefined||value===null||value==='')return null;const result=requiredString(value,'page_token',1,2048);if(!/^[A-Za-z0-9_-]+$/.test(result))throw new RequestValidationError('page_token is invalid');return result}
function optionalGhlId(value:unknown,field:string):string|null{if(value===undefined||value===null||value==='')return null;const result=requiredString(value,field,1,128);if(!/^[A-Za-z0-9_-]+$/.test(result))throw new RequestValidationError(`${field} is invalid`);return result}
function optionalString(value:unknown,field:string,minimum:number,maximum:number):string|null{if(value===undefined||value===null||value==='')return null;return requiredString(value,field,minimum,maximum)}
function optionalEnum<const T extends readonly string[]>(value:unknown,field:string,allowed:T):T[number]|null{if(value===undefined||value===null||value==='')return null;if(typeof value!=='string'||!allowed.includes(value))throw new RequestValidationError(`${field} is invalid`);return value as T[number]}
function optionalUuid(value:unknown,field:string):string|null{if(value===undefined||value===null||value==='')return null;return uuid(value,field)}
function uuid(value:unknown,field:string):string{const result=requiredString(value,field,36,36).toLowerCase();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(result))throw new RequestValidationError(`${field} is invalid`);return result}
function requiredString(value:unknown,field:string,minimum:number,maximum:number):string{if(typeof value!=='string')throw new RequestValidationError(`${field} must be a string`);const result=value.trim();if(result.length<minimum||result.length>maximum)throw new RequestValidationError(`${field} must be between ${minimum} and ${maximum} characters`);return result}
function optionalInteger(value:unknown,field:string,minimum:number,maximum:number):number|null{if(value===undefined||value===null)return null;if(!Number.isSafeInteger(value)||Number(value)<minimum||Number(value)>maximum)throw new RequestValidationError(`${field} must be an integer between ${minimum} and ${maximum}`);return Number(value)}
function optionalNumber(value:unknown,field:string,minimum:number,maximum:number):number|null{if(value===undefined||value===null||value==='')return null;if(typeof value!=='number'||!Number.isFinite(value)||value<minimum||value>maximum)throw new RequestValidationError(`${field} must be a number between ${minimum} and ${maximum}`);return value}
function requiredNumber(value:unknown,field:string,minimum:number,maximum:number):number{const result=optionalNumber(value,field,minimum,maximum);if(result===null)throw new RequestValidationError(`${field} is required`);return result}
function intakeFactUpdates(value:unknown,field:string):Record<string,string|number|boolean|null>{if(value===undefined||value===null)return{};if(!isRecord(value))throw new RequestValidationError(`${field} must be an object`);const out:Record<string,string|number|boolean|null>={};for(const[key,raw]of Object.entries(value)){if(!INTAKE_FACT_KEYS.has(key))throw new RequestValidationError(`${field}.${key} is not allowed`);if(raw===null){out[key]=null}else if(typeof raw==='string'){const v=raw.trim();if(!v||v.length>1000)throw new RequestValidationError(`${field}.${key} is invalid`);out[key]=v}else if(typeof raw==='number'&&Number.isFinite(raw)){out[key]=raw}else if(typeof raw==='boolean'){out[key]=raw}else throw new RequestValidationError(`${field}.${key} must be a string, number, boolean, or null`)}return out}
function intakeEvidence(value:unknown,field:string):Record<string,unknown>{if(value===undefined||value===null)return{};if(!isRecord(value))throw new RequestValidationError(`${field} must be an object`);const email=boundedStringArray(value.email,`${field}.email`,20,2000),attachment=boundedStringArray(value.attachment,`${field}.attachment`,20,2000),conflicts:Record<string,string>={};if(value.source_conflict!==undefined&&value.source_conflict!==null){if(!isRecord(value.source_conflict))throw new RequestValidationError(`${field}.source_conflict must be an object`);const entries=Object.entries(value.source_conflict);if(entries.length>20)throw new RequestValidationError(`${field}.source_conflict has too many entries`);for(const[key,raw]of entries){const k=key.trim();if(!k||k.length>120||typeof raw!=='string'||!raw.trim()||raw.trim().length>2000)throw new RequestValidationError(`${field}.source_conflict is invalid`);conflicts[k]=raw.trim()}}const out:Record<string,unknown>={};if(email.length)out.email=email;if(attachment.length)out.attachment=attachment;if(Object.keys(conflicts).length)out.source_conflict=conflicts;return out}
function emailIntakeInput(input:Record<string,unknown>):Record<string,unknown>{const messageId=gmailId(input.message_id,'message_id'),disposition=optionalEnum(input.message_disposition,'message_disposition',['deal','excluded'] as const);if(!disposition)throw new RequestValidationError('message_disposition is required');const exclusionReason=optionalString(input.exclusion_reason,'exclusion_reason',1,500);const rawCandidates=input.candidates??[];if(!Array.isArray(rawCandidates)||rawCandidates.length>20)throw new RequestValidationError('candidates must be an array with at most 20 items');if(disposition==='excluded'){if(rawCandidates.length)throw new RequestValidationError('excluded messages cannot include candidates');return{message_id:messageId,message_disposition:disposition,exclusion_reason:exclusionReason,candidates:[]}}if(!rawCandidates.length)throw new RequestValidationError('deal messages require at least one candidate');const candidates=rawCandidates.map((raw,index)=>{if(!isRecord(raw))throw new RequestValidationError(`candidates[${index}] must be an object`);const intakeResult=optionalEnum(raw.intake_result,`candidates[${index}].intake_result`,['supported','excluded','needs_classification','needs_info'] as const)??'supported';const sourceType=optionalEnum(raw.source_type,`candidates[${index}].source_type`,['email','attachment','mixed'] as const)??'email';return{candidate_type:optionalString(raw.candidate_type,`candidates[${index}].candidate_type`,1,120),normalized_address:optionalString(raw.normalized_address,`candidates[${index}].normalized_address`,1,300),extracted_facts:intakeFactUpdates(raw.extracted_facts,`candidates[${index}].extracted_facts`),evidence:intakeEvidence(raw.evidence,`candidates[${index}].evidence`),missing_information:boundedStringArray(raw.missing_information,`candidates[${index}].missing_information`,30,500),source_type:sourceType,intake_result:intakeResult}});return{message_id:messageId,message_disposition:disposition,exclusion_reason:null,candidates}}
function boundedStringArray(value:unknown,field:string,maxItems:number,maxLength:number):string[]{if(value===undefined||value===null)return[];if(!Array.isArray(value)||value.length>maxItems)throw new RequestValidationError(`${field} must be an array with at most ${maxItems} items`);return value.map((raw,index)=>requiredString(raw,`${field}[${index}]`,1,maxLength))}
function reconcileFactUpdates(value:unknown):Record<string,string|number|boolean>{if(value===undefined||value===null)return{};if(!isRecord(value))throw new RequestValidationError('fact_updates must be an object');const out:Record<string,string|number|boolean>={};for(const[key,raw]of Object.entries(value)){if(!RECONCILE_FACT_KEYS.has(key))throw new RequestValidationError(`fact_updates.${key} is not allowed`);if(typeof raw==='string'){const v=raw.trim();if(!v||v.length>1000)throw new RequestValidationError(`fact_updates.${key} is invalid`);out[key]=v}else if(typeof raw==='number'&&Number.isFinite(raw)){out[key]=raw}else if(typeof raw==='boolean'){out[key]=raw}else throw new RequestValidationError(`fact_updates.${key} must be a string, number, or boolean`)}return out}
function reconcileDocuments(value:unknown):Array<{attachment_id:string;document_type:typeof PORTFOLIO_DOCUMENT_TYPES[number]}> {if(value===undefined||value===null)return[];if(!Array.isArray(value)||value.length>8)throw new RequestValidationError('documents must be an array with at most 8 items');return value.map((item,index)=>{if(!isRecord(item))throw new RequestValidationError(`documents[${index}] must be an object`);const attachmentId=gmailId(item.attachment_id,`documents[${index}].attachment_id`),documentType=optionalEnum(item.document_type,`documents[${index}].document_type`,PORTFOLIO_DOCUMENT_TYPES);if(!documentType)throw new RequestValidationError(`documents[${index}].document_type is required`);return{attachment_id:attachmentId,document_type:documentType}})}
function cashValueInput(input:Record<string,unknown>):Record<string,unknown>{
  const candidateId=optionalUuid(input.candidate_id,'candidate_id'),opportunityId=optionalGhlId(input.opportunity_id,'opportunity_id');
  if(candidateId||opportunityId){
    if(candidateId&&opportunityId)throw new RequestValidationError('candidate_id and opportunity_id are mutually exclusive');
    return{candidate_id:candidateId,opportunity_id:opportunityId,subject_evidence:publicSubjectEvidence(input.subject_evidence),public_comps:publicEvidenceComps(input.public_comps)};
  }
  if(!isRecord(input.subject))throw new RequestValidationError('candidate_id, opportunity_id, or subject is required');
  if(!Array.isArray(input.comps)||input.comps.length>50)throw new RequestValidationError('comps must be an array with at most 50 items');
  const subject=cashValueProperty(input.subject,'subject',false);
  const comps=input.comps.map((raw,index)=>{if(!isRecord(raw))throw new RequestValidationError(`comps[${index}] must be an object`);return cashValueProperty(raw,`comps[${index}]`,true)});
  const valuationDate=optionalString(input.valuation_date,'valuation_date',10,10);if(valuationDate&&!/^\d{4}-\d{2}-\d{2}$/.test(valuationDate))throw new RequestValidationError('valuation_date must be YYYY-MM-DD');
  return{subject,comps,valuation_date:valuationDate};
}
function rehabInput(input:Record<string,unknown>):Record<string,unknown>{
  assertOnlyKeys(input,new Set(['opportunity_id','scope_items']),'underwriting.rehab');
  const opportunityId=optionalGhlId(input.opportunity_id,'opportunity_id');if(!opportunityId)throw new RequestValidationError('opportunity_id is required');
  if(!Array.isArray(input.scope_items)||input.scope_items.length<1||input.scope_items.length>50)throw new RequestValidationError('scope_items must contain between 1 and 50 items');
  const scopeItems=input.scope_items.map((raw,index)=>{
    if(!isRecord(raw))throw new RequestValidationError(`scope_items[${index}] must be an object`);
    assertOnlyKeys(raw,new Set(['category','scope_level','description','evidence_class','source_type','source_ref','quantity']),`scope_items[${index}]`);
    const category=optionalEnum(raw.category,`scope_items[${index}].category`,REHAB_CATEGORIES);if(!category)throw new RequestValidationError(`scope_items[${index}].category is required`);
    const scopeLevel=optionalEnum(raw.scope_level,`scope_items[${index}].scope_level`,REHAB_SCOPE_LEVELS);if(!scopeLevel)throw new RequestValidationError(`scope_items[${index}].scope_level is required`);
    const evidenceClass=optionalEnum(raw.evidence_class,`scope_items[${index}].evidence_class`,REHAB_EVIDENCE_CLASSES);if(!evidenceClass)throw new RequestValidationError(`scope_items[${index}].evidence_class is required`);
    const sourceType=optionalEnum(raw.source_type,`scope_items[${index}].source_type`,REHAB_SOURCE_TYPES);if(!sourceType)throw new RequestValidationError(`scope_items[${index}].source_type is required`);
    return{category,scope_level:scopeLevel,description:requiredString(raw.description,`scope_items[${index}].description`,1,500),evidence_class:evidenceClass,source_type:sourceType,source_ref:requiredString(raw.source_ref,`scope_items[${index}].source_ref`,1,1000),quantity:optionalNumber(raw.quantity,`scope_items[${index}].quantity`,0.01,1000000)};
  });
  return{opportunity_id:opportunityId,scope_items:scopeItems};
}
function assertOnlyKeys(value:Record<string,unknown>,allowed:Set<string>,field:string):void{for(const key of Object.keys(value))if(!allowed.has(key))throw new RequestValidationError(`${field}.${key} is not allowed`)}
function publicSubjectEvidence(value:unknown):Record<string,unknown>|null{
  if(value===undefined||value===null)return null;if(!isRecord(value))throw new RequestValidationError('subject_evidence must be an object');
  const result:Record<string,unknown>={source_url:publicSourceUrl(value.source_url,'subject_evidence.source_url'),source_name:optionalString(value.source_name,'subject_evidence.source_name',1,120),sqft:optionalNumber(value.sqft,'subject_evidence.sqft',1,50000),year_built:optionalNumber(value.year_built,'subject_evidence.year_built',1600,2200),beds:optionalNumber(value.beds,'subject_evidence.beds',0,50),baths:optionalNumber(value.baths,'subject_evidence.baths',0,50),stories:optionalNumber(value.stories,'subject_evidence.stories',0,20),build_style:optionalString(value.build_style,'subject_evidence.build_style',1,120)};
  if(!['sqft','year_built','beds','baths','stories','build_style'].some(key=>result[key]!==null))throw new RequestValidationError('subject_evidence must include at least one property fact');return result;
}
function publicEvidenceComps(value:unknown):Array<Record<string,unknown>>{
  if(value===undefined||value===null)return[];if(!Array.isArray(value)||value.length>25)throw new RequestValidationError('public_comps must be an array with at most 25 items');
  return value.map((raw,index)=>{if(!isRecord(raw))throw new RequestValidationError(`public_comps[${index}] must be an object`);const comp=cashValueProperty(raw,`public_comps[${index}]`,true);comp.source=publicSourceUrl(raw.source_url,`public_comps[${index}].source_url`);comp.source_name=optionalString(raw.source_name,`public_comps[${index}].source_name`,1,120);return comp});
}
function publicSourceUrl(value:unknown,field:string):string{
  const raw=requiredString(value,field,8,1000);let parsed:URL;try{parsed=new URL(raw)}catch{throw new RequestValidationError(`${field} must be a valid URL`)}
  const host=parsed.hostname.toLowerCase();if(parsed.protocol!=='https:'||!host.includes('.')||host==='localhost'||host.endsWith('.local')||/^\[?[0-9a-f:.]+\]?$/i.test(host))throw new RequestValidationError(`${field} must be a public HTTPS URL`);return parsed.toString();
}
function cashValueProperty(value:Record<string,unknown>,field:string,isComp:boolean):Record<string,unknown>{const result:Record<string,unknown>={address:optionalString(value.address,`${field}.address`,1,300),property_type:requiredString(value.property_type,`${field}.property_type`,1,120),sqft:requiredNumber(value.sqft,`${field}.sqft`,1,50000),year_built:optionalNumber(value.year_built,`${field}.year_built`,1600,2200),beds:optionalNumber(value.beds,`${field}.beds`,0,50),baths:optionalNumber(value.baths,`${field}.baths`,0,50),stories:optionalNumber(value.stories,`${field}.stories`,0,20),build_style:optionalString(value.build_style,`${field}.build_style`,1,120)};if(isComp){result.id=optionalString(value.id,`${field}.id`,1,128);result.condition=optionalString(value.condition,`${field}.condition`,1,120);result.sale_price=requiredNumber(value.sale_price,`${field}.sale_price`,1,1000000000);result.sale_date=requiredString(value.sale_date,`${field}.sale_date`,10,32);if(Number.isNaN(new Date(String(result.sale_date)).getTime()))throw new RequestValidationError(`${field}.sale_date is invalid`);result.distance_miles=requiredNumber(value.distance_miles,`${field}.distance_miles`,0,100);result.source=optionalString(value.source,`${field}.source`,1,1000);if(!result.address)throw new RequestValidationError(`${field}.address is required`)}return result}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value)}