import type { SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2.95.0';
import { createGhlContact, createGhlContactNote, createGhlOpportunity, getGhlContact, getGhlOpportunity, listGhlContactNotes, searchGhlContacts, searchGhlOpportunities, updateGhlOpportunity, type GhlContext } from '../_shared/ghl.ts';

const SFR_PIPELINE_ID='w3OtDJjCdN840Hwb1fpt',SFR_STAGE_ID='a4842558-034c-4ba7-acf3-ed000673f7d6',PORTFOLIO_PIPELINE_ID='K6YsnZw6qhYLvXSvuixD',PORTFOLIO_STAGE_ID='4513320f-0972-4b4a-9e37-dee4d71e1843';
const FIELD_IDS={property_type:'36WeaPwncmXLzUQhbGHd',asking_price:'hVo62cSBHESpSpJQ2QoX',full_address:'hH02pevCKOTpmDYfOTnu',zip:'BXGXMg5dA8kfSVEsYjwI',state:'TNuP3h0jHhlwLWUSNK2x',county:'tsyE3j0AnrAmac5aTaeb',occupancy:'24s6rwssx0W3093tEo2h',mortgage_status:'611ub7w9MMhUqwbe2bj0',mortgage_balance:'WfVQ5inw4CoaFYQ5PsAW',arrears:'dsOJSTUvwgUgqYMtrO2m',piti:'mtYnZP37vV0uOTkPfceQ',timeline:'BTXkC4oHbvE7cczlZnaP',motivation:'7gob9JukkaLf8DCYCZSE',condition:'mDmONnuCOpGGzdYTHodv',hoa:'PR32yVuxmSeYGiAbaCkv',hoa_amount:'BFNjLczMo7vYEnHlSbck',hoa_restrictions:'o8OJwL6sL5cp3e8yOlHG',hoa_duration:'ejOAWgQ2iduRGGJfBSDL',listed:'650RG6IFagUe3STMpFYu',flood_utilities:'Xjbfg8zqPgLmC2iyugTC',deal_details:'01yCBq5RVjHvCuAFCFVY',deal_type:'SLOZCx6t83950AfnuPqO',photos_zillow:'kgMWUBZEmTutUT9neFN9'} as const;
const SUBJECT_LIKE_ADDRESS=/\b(new lead|price drop|property info request|properties available|business for sale|off market opportunity)\b/i;
export class DealIntakeError extends Error{constructor(public status:number,public code:string){super(code);this.name='DealIntakeError'}}
interface CandidateRow{id:string;workspace_id:string;ema_message_id:string;normalized_address:string|null;extracted_facts:Record<string,unknown>;evidence:Record<string,unknown>;source_type:string|null;intake_result:string|null;cash_screen_result:string;buy_box_fit_result:string;buy_box_fit_details:Record<string,unknown>;ghl_readiness:string;ghl_contact_id:string|null;ghl_opportunity_id:string|null;processing_status:string;is_test:boolean}
interface MessageRow{id:string;gmail_message_id:string;gmail_thread_id:string;sender_email:string|null;sender_name:string|null;subject:string|null;raw_metadata:Record<string,unknown>}
interface Route{propertyType:string;pipelineId:string;stageId:string}
interface OperationRow{id:string;operation_status:string;external_id:string|null}

export async function intakeCandidateToCrm(admin:SupabaseClient,ghl:GhlContext,workspaceId:string,candidateId:string):Promise<Record<string,unknown>>{const candidate=await loadCandidate(admin,workspaceId,candidateId),message=await loadMessage(admin,workspaceId,candidate.ema_message_id);validateCandidate(candidate);const address=candidate.normalized_address!.trim(),route=deriveRoute(candidate.extracted_facts),customFields=buildOpportunityCustomFields(candidate,address,route);await admin.from('ema_candidates').update({processing_status:'ghl_pending',last_evaluated_at:new Date().toISOString()}).eq('id',candidate.id).eq('workspace_id',workspaceId);const contact=await resolveContact(admin,ghl,candidate,message),opportunity=await resolveOpportunity(admin,ghl,candidate,address,route,contact.id,customFields),note=await ensureIntakeNote(admin,ghl,candidate,message,address,contact.id,opportunity.id,opportunity.created),{error}=await admin.from('ema_candidates').update({ghl_contact_id:contact.id,ghl_opportunity_id:opportunity.id,ghl_readiness:'ready',processing_status:'completed',last_evaluated_at:new Date().toISOString()}).eq('id',candidate.id).eq('workspace_id',workspaceId);if(error)throw new DealIntakeError(500,'candidate_persist_failed');const qualificationSource=isEmaCrmIntakeEligible(candidate.buy_box_fit_result)?'ema_buy_box_fit':'cash_screen';return{candidate_id:candidate.id,qualification:{source:qualificationSource,buy_box_fit_result:candidate.buy_box_fit_result,verification_status:recordString(candidate.buy_box_fit_details,'verification_status'),cash_verdict:candidate.cash_screen_result},contact:{id:contact.id,disposition:contact.disposition},opportunity:{id:opportunity.id,disposition:opportunity.created?'created':'matched',pipeline_id:opportunity.pipelineId,stage_id:opportunity.stageId},note:{id:note.id,target:'contact',opportunity_id:opportunity.id,disposition:note.disposition}}}
async function loadCandidate(admin:SupabaseClient,w:string,id:string):Promise<CandidateRow>{const{data,error}=await admin.from('ema_candidates').select('id, workspace_id, ema_message_id, normalized_address, extracted_facts, evidence, source_type, intake_result, cash_screen_result, buy_box_fit_result, buy_box_fit_details, ghl_readiness, ghl_contact_id, ghl_opportunity_id, processing_status, is_test').eq('id',id).eq('workspace_id',w).maybeSingle();if(error)throw new DealIntakeError(500,'candidate_lookup_failed');if(!data)throw new DealIntakeError(404,'candidate_not_found');return data as CandidateRow}
async function loadMessage(admin:SupabaseClient,w:string,id:string):Promise<MessageRow>{const{data,error}=await admin.from('ema_messages').select('id, gmail_message_id, gmail_thread_id, sender_email, sender_name, subject, raw_metadata').eq('id',id).eq('workspace_id',w).maybeSingle();if(error)throw new DealIntakeError(500,'ema_message_lookup_failed');if(!data)throw new DealIntakeError(409,'ema_message_missing');return data as MessageRow}
function validateCandidate(c:CandidateRow){if(c.is_test)throw new DealIntakeError(409,'test_candidate_not_permitted');const emaCrmEligible=isEmaCrmIntakeEligible(c.buy_box_fit_result),cashQualified=['pass','marginal'].includes(c.cash_screen_result);if(!emaCrmEligible&&!cashQualified)throw new DealIntakeError(409,'deal_qualification_required');if(['excluded','needs_classification','needs_info'].includes(c.intake_result??'')||c.ghl_readiness==='excluded')throw new DealIntakeError(409,'candidate_not_intake_eligible');if(!looksLikeResolvedAddress(c.normalized_address?.trim()??''))throw new DealIntakeError(409,'normalized_address_required')}
export function isEmaCrmIntakeEligible(result:string):boolean{return result==='fit'||result==='needs_info'}
export function looksLikeResolvedAddress(a:string):boolean{if(a.length<8||a.length>300||SUBJECT_LIKE_ADDRESS.test(a))return false;return /^\s*\d{1,8}\s+[A-Za-z0-9]/.test(a)}
export function deriveRoute(f:Record<string,unknown>):Route{const t=cleanString(firstValue(f,['property_type','propertyType','asset_class','assetClass','type']),120)?.toLowerCase()??'',u=numberValue(firstValue(f,['units','unit_count','unitCount','number_of_units','site_count','pad_count']));if(/\brv\s*park\b|recreational vehicle park/.test(t))return{propertyType:'RV Park',pipelineId:PORTFOLIO_PIPELINE_ID,stageId:PORTFOLIO_STAGE_ID};if(/mobile\s*home\s*park|\bmhp\b/.test(t))return{propertyType:'Mobile Home Park',pipelineId:PORTFOLIO_PIPELINE_ID,stageId:PORTFOLIO_STAGE_ID};if(/town\s*house|townhome/.test(t))return{propertyType:'Townhouse',pipelineId:SFR_PIPELINE_ID,stageId:SFR_STAGE_ID};if(/attached/.test(t)&&!/multi/.test(t))return{propertyType:'Attached',pipelineId:SFR_PIPELINE_ID,stageId:SFR_STAGE_ID};if(/duplex|triplex|fourplex|2\s*[-–]\s*4|multi[- ]?family\s*2/.test(t)||(u!==null&&u>=2&&u<=4))return{propertyType:'Multi-family 2-4',pipelineId:SFR_PIPELINE_ID,stageId:SFR_STAGE_ID};if(/multi[- ]?family|apartment|multifamily/.test(t)&&(u===null||u>=5))return{propertyType:'Multi-family 5+',pipelineId:PORTFOLIO_PIPELINE_ID,stageId:PORTFOLIO_STAGE_ID};if(/single[- ]?family|\bsfr\b|detached/.test(t)||u===1)return{propertyType:'SFR',pipelineId:SFR_PIPELINE_ID,stageId:SFR_STAGE_ID};throw new DealIntakeError(409,'property_type_unresolved')}

async function resolveContact(admin:SupabaseClient,ghl:GhlContext,c:CandidateRow,m:MessageRow):Promise<{id:string;disposition:'matched'|'created'|'persisted'}>{if(c.ghl_contact_id){const x=await getGhlContact(ghl,c.ghl_contact_id);if(!x.id)throw new DealIntakeError(409,'persisted_contact_invalid');return{id:x.id,disposition:'persisted'}}const email=cleanString(m.sender_email,320)?.toLowerCase()??null;if(!email)throw new DealIntakeError(409,'sender_identity_required');const es=await searchGhlContacts(ghl,{query:email,page:1,limit:20}),em=recordArray(es.contacts).filter(r=>cleanString(r.email,320)?.toLowerCase()===email);if(em.length>1)throw new DealIntakeError(409,'contact_match_ambiguous');if(em.length===1)return{id:requiredId(em[0].id),disposition:'matched'};const phone=cleanString(firstValue(c.extracted_facts,['sender_phone','phone','broker_phone']),64);if(phone){const ps=await searchGhlContacts(ghl,{query:phone,page:1,limit:20}),n=normalizePhone(phone),pm=recordArray(ps.contacts).filter(r=>normalizePhone(cleanString(r.phone,64)??'')===n);if(pm.length>1)throw new DealIntakeError(409,'contact_match_ambiguous');if(pm.length===1)return{id:requiredId(pm[0].id),disposition:'matched'}}const key=`ema:${c.id}:contact:v1`,prior=await getOperation(admin,c.workspace_id,key);if(prior?.operation_status==='succeeded'&&prior.external_id)return{id:prior.external_id,disposition:'persisted'};if(prior&&['executing','needs_reconciliation'].includes(prior.operation_status))throw new DealIntakeError(409,'contact_create_requires_reconciliation');const op=await beginOperation(admin,c,'ghl_contact_upsert',key);try{const made=await createGhlContact(ghl,{firstName:firstName(m.sender_name),lastName:lastName(m.sender_name),name:cleanString(m.sender_name,300),email,phone,companyName:cleanString(firstValue(c.extracted_facts,['sender_company','company','broker_company']),300),source:'Ema Email Intake',tags:controlledContactTags(c)}),id=requiredId(made.id);await finishOperation(admin,op.id,id,{created:true});return{id,disposition:'created'}}catch(e){await markOperationUncertain(admin,op.id,e);throw e}}
async function resolveOpportunity(admin:SupabaseClient,ghl:GhlContext,c:CandidateRow,address:string,route:Route,contactId:string,customFields:Array<Record<string,unknown>>):Promise<{id:string;created:boolean;pipelineId:string;stageId:string}>{if(c.ghl_opportunity_id){const x=await getGhlOpportunity(ghl,c.ghl_opportunity_id),id=requiredId(x.id),ec=cleanString(x.contact_id,128);if(ec&&ec!==contactId)throw new DealIntakeError(409,'persisted_opportunity_contact_mismatch');if(customFields.length)await updateExistingOpportunityFields(admin,ghl,c,id,customFields);return{id,created:false,pipelineId:requiredId(x.pipeline_id),stageId:requiredId(x.stage_id)}}const s=await searchGhlOpportunities(ghl,{query:address,page:1,limit:50}),exact=recordArray(s.opportunities).filter(r=>canonicalAddress(cleanString(r.name,500)??'')===canonicalAddress(address));if(exact.length>1)throw new DealIntakeError(409,'opportunity_match_ambiguous');if(exact.length===1){const r=exact[0],id=requiredId(r.id),fc=cleanString(r.contact_id,128);if(fc&&fc!==contactId)throw new DealIntakeError(409,'opportunity_contact_mismatch');if(customFields.length)await updateExistingOpportunityFields(admin,ghl,c,id,customFields);return{id,created:false,pipelineId:requiredId(r.pipeline_id),stageId:requiredId(r.stage_id)}}const key=`ema:${c.id}:opportunity:v1`,prior=await getOperation(admin,c.workspace_id,key);if(prior?.operation_status==='succeeded'&&prior.external_id){const x=await getGhlOpportunity(ghl,prior.external_id);return{id:prior.external_id,created:false,pipelineId:requiredId(x.pipeline_id),stageId:requiredId(x.stage_id)}}if(prior&&['executing','needs_reconciliation'].includes(prior.operation_status))throw new DealIntakeError(409,'opportunity_create_requires_reconciliation');const op=await beginOperation(admin,c,'ghl_opportunity_create',key);try{const made=await createGhlOpportunity(ghl,{pipelineId:route.pipelineId,pipelineStageId:route.stageId,name:address,status:'open',contactId,customFields}),id=requiredId(made.id);await finishOperation(admin,op.id,id,{pipeline_id:route.pipelineId,stage_id:route.stageId});return{id,created:true,pipelineId:route.pipelineId,stageId:route.stageId}}catch(e){await markOperationUncertain(admin,op.id,e);throw e}}
async function updateExistingOpportunityFields(admin:SupabaseClient,ghl:GhlContext,c:CandidateRow,id:string,fields:Array<Record<string,unknown>>){const key=`ema:${c.id}:opportunity-fields:v1`,prior=await getOperation(admin,c.workspace_id,key);if(prior?.operation_status==='succeeded')return;if(prior&&['executing','needs_reconciliation'].includes(prior.operation_status))throw new DealIntakeError(409,'opportunity_update_requires_reconciliation');const op=await beginOperation(admin,c,'ghl_opportunity_update',key);try{await updateGhlOpportunity(ghl,id,{customFields:fields});await finishOperation(admin,op.id,id,{fields_updated:fields.length})}catch(e){await markOperationUncertain(admin,op.id,e);throw e}}
async function ensureIntakeNote(admin:SupabaseClient,ghl:GhlContext,c:CandidateRow,m:MessageRow,address:string,contactId:string,oppId:string,created:boolean):Promise<{id:string;disposition:'created'|'reconciled'|'persisted'}>{const body=buildNoteBody(c,m,address,oppId,created?'INITIAL REVIEW':'NEW INFORMATION'),key=`ema:${m.gmail_message_id}:${oppId}:note:v1`,prior=await getOperation(admin,c.workspace_id,key);if(prior?.operation_status==='succeeded'&&prior.external_id)return{id:prior.external_id,disposition:'persisted'};const notes=await listGhlContactNotes(ghl,contactId),marker=`Intake Ref: ${c.id}`,existing=recordArray(notes.notes).find(r=>cleanString(r.body,5000)?.includes(marker));if(existing){const id=requiredId(existing.id);if(prior)await finishOperation(admin,prior.id,id,{reconciled:true});return{id,disposition:'reconciled'}}if(prior&&['executing','needs_reconciliation'].includes(prior.operation_status))throw new DealIntakeError(409,'note_create_requires_reconciliation');const op=await beginOperation(admin,c,'ghl_opportunity_note_create',key);try{const made=await createGhlContactNote(ghl,contactId,body),id=requiredId(made.id);await finishOperation(admin,op.id,id,{target:'contact',opportunity_id:oppId});return{id,disposition:'created'}}catch(e){await markOperationUncertain(admin,op.id,e);throw e}}

function buildOpportunityCustomFields(c:CandidateRow,address:string,route:Route){const f=c.extracted_facts,out:Array<Record<string,unknown>>=[];addField(out,FIELD_IDS.property_type,route.propertyType);addField(out,FIELD_IDS.full_address,address);for(const[id,keys]of[[FIELD_IDS.asking_price,['asking_price','askingPrice','price']],[FIELD_IDS.zip,['zip','zipcode','postal_code','postalCode']],[FIELD_IDS.state,['state','property_state']],[FIELD_IDS.county,['county','property_county']],[FIELD_IDS.occupancy,['occupancy','occupancy_status']],[FIELD_IDS.mortgage_status,['mortgage_status','mortgageStatus']],[FIELD_IDS.mortgage_balance,['mortgage_balance','mortgageBalance']],[FIELD_IDS.arrears,['back_payments','arrears','backPayments']],[FIELD_IDS.piti,['piti','PITI']],[FIELD_IDS.timeline,['timeline','seller_timeline']],[FIELD_IDS.motivation,['motivation','seller_motivation']],[FIELD_IDS.condition,['condition','property_condition']],[FIELD_IDS.hoa,['hoa','has_hoa','hoa_exists']],[FIELD_IDS.hoa_amount,['hoa_amount','hoaAmount']],[FIELD_IDS.hoa_restrictions,['hoa_restrictions','hoaRestrictions']],[FIELD_IDS.hoa_duration,['hoa_frequency','hoa_duration','hoaFrequency']],[FIELD_IDS.listed,['listed_with_realtor','listed','listing_status']],[FIELD_IDS.flood_utilities,['flood_and_utilities_info','flood_utilities']],[FIELD_IDS.deal_type,['deal_type','dealType']],[FIELD_IDS.photos_zillow,['photos_zillow','photos_url','zillow_url','deal_room_url']]]as Array<[string,string[]]>)addField(out,id,firstValue(f,keys));const d=buildDealDetails(f);if(d)addField(out,FIELD_IDS.deal_details,d);return out}
function buildDealDetails(f:Record<string,unknown>){const p:Array<[string,unknown]>=[['Units',firstValue(f,['units','unit_count','unitCount'])],['Occupancy',firstValue(f,['occupancy','occupancy_status'])],['Condition',firstValue(f,['condition','property_condition'])],['Timeline',firstValue(f,['timeline','seller_timeline'])],['Deal Type',firstValue(f,['deal_type','dealType'])]],l=p.flatMap(([a,v])=>{const s=scalarString(v,300);return s?[`${a}: ${s}`]:[]});return l.length?l.join('\n').slice(0,3000):null}
function buildNoteBody(c:CandidateRow,m:MessageRow,address:string,oppId:string,event:string){const f=c.extracted_facts,l=[`EMA | ${address} | ${event}`,''];if(c.buy_box_fit_result==='fit'){const verification=recordString(c.buy_box_fit_details,'verification_status')??'provisional';l.push(`Preliminary Buy-Box Fit: FIT (${verification.toUpperCase()})`)}else if(c.buy_box_fit_result==='needs_info'){l.push('Preliminary Buy-Box Fit: NEEDS INFO (TEAM REVIEW)');const missing=buyBoxUnknownFields(c.buy_box_fit_details);if(missing.length)l.push(`Missing/Unknown: ${missing.join(', ')}`)}else if(['pass','marginal'].includes(c.cash_screen_result))l.push(`Cash Screen: ${c.cash_screen_result.toUpperCase()}`);l.push('Source: Email');if(m.sender_name)l.push(`Sender: ${m.sender_name.slice(0,200)}`);if(m.sender_email)l.push(`Sender Email: ${m.sender_email.slice(0,320)}`);for(const[label,keys]of[['Asking Price',['asking_price','askingPrice','price']],['Property Type',['property_type','propertyType','asset_class']],['Occupancy',['occupancy','occupancy_status']]]as Array<[string,string[]]>){const s=scalarString(firstValue(f,keys),160);if(s)l.push(`${label}: ${s}`)}l.push('',`Opportunity ID: ${oppId}`,`Gmail Message: ${m.gmail_message_id.slice(0,300)}`,`Intake Ref: ${c.id}`);return l.join('\n').slice(0,5000)}
function buyBoxUnknownFields(details:Record<string,unknown>):string[]{return recordArray(details.unknown).flatMap(r=>{const field=cleanString(r.field,120);return field?[field]:[]})}
function controlledContactTags(c:CandidateRow){const status=c.buy_box_fit_result==='needs_info'?'ema-needs-info':(c.buy_box_fit_result==='fit'||c.cash_screen_result==='pass')?'ema-qualified':'ema-marginal',t=['email-lead',status],s=c.source_type?.toLowerCase()??'';if(s.includes('broker'))t.push('broker');else if(s.includes('wholesale'))t.push('wholesaler');else if(s.includes('seller'))t.push('direct-seller');else if(s.includes('agent'))t.push('agent');else if(s.includes('lender'))t.push('lender');return t}

async function getOperation(admin:SupabaseClient,w:string,key:string):Promise<OperationRow|null>{const{data,error}=await admin.from('ema_operations').select('id, operation_status, external_id').eq('workspace_id',w).eq('operating_mode','autonomous').eq('idempotency_key',key).maybeSingle();if(error)throw new DealIntakeError(500,'ema_operation_lookup_failed');return data as OperationRow|null}
async function beginOperation(admin:SupabaseClient,c:CandidateRow,type:string,key:string):Promise<OperationRow>{const{data,error}=await admin.from('ema_operations').insert({workspace_id:c.workspace_id,ema_message_id:c.ema_message_id,ema_candidate_id:c.id,operating_mode:'autonomous',operation_type:type,idempotency_key:key,operation_status:'executing',request_metadata:{source:'agent_gateway',contract:'deal.intake_to_crm.v2'},attempt_count:1,is_test:false}).select('id, operation_status, external_id').single();if(error||!data)throw new DealIntakeError(500,'ema_operation_create_failed');return data as OperationRow}
async function finishOperation(admin:SupabaseClient,id:string,externalId:string,meta:Record<string,unknown>){const{error}=await admin.from('ema_operations').update({operation_status:'succeeded',external_id:externalId,result_metadata:meta,last_error:null}).eq('id',id);if(error)throw new DealIntakeError(500,'ema_operation_update_failed')}
async function markOperationUncertain(admin:SupabaseClient,id:string,e:unknown){await admin.from('ema_operations').update({operation_status:'needs_reconciliation',last_error:e instanceof Error?e.name.slice(0,120):'upstream_error'}).eq('id',id)}
function addField(a:Array<Record<string,unknown>>,id:string,v:unknown){const s=scalarString(v,3000);if(s!==null)a.push({id,fieldValue:s})}
function firstValue(r:Record<string,unknown>,keys:string[]){for(const k of keys){const v=r[k];if(v!==undefined&&v!==null&&v!=='')return v}return null}
function scalarString(v:unknown,max:number):string|null{if(typeof v==='string'){const s=v.trim();return s?s.slice(0,max):null}if(typeof v==='number'&&Number.isFinite(v))return String(v).slice(0,max);if(typeof v==='boolean')return v?'Yes':'No';return null}
function cleanString(v:unknown,m:number){return scalarString(v,m)}
function numberValue(v:unknown){if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'){const n=Number(v.replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:null}return null}
function recordArray(v:unknown):Array<Record<string,unknown>>{return Array.isArray(v)?v.filter((x):x is Record<string,unknown>=>typeof x==='object'&&x!==null&&!Array.isArray(x)):[]}
function requiredId(v:unknown){const id=cleanString(v,128);if(!id||!/^[A-Za-z0-9_-]+$/.test(id))throw new DealIntakeError(502,'invalid_ghl_identifier');return id}
function canonicalAddress(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'')}
function normalizePhone(v:string){return v.replace(/\D/g,'').slice(-10)}
function firstName(n:string|null){const c=cleanString(n,300);return c?c.split(/\s+/)[0].slice(0,100):null}
function lastName(n:string|null){const c=cleanString(n,300);if(!c)return null;const p=c.split(/\s+/);return p.length>1?p.slice(1).join(' ').slice(0,150):null}
function recordString(value:Record<string,unknown>,key:string):string|null{return typeof value[key]==='string'?String(value[key]).slice(0,160):null}
