import { emailInputValidators } from "./schemas.ts";

function assert(condition: unknown,message = "Assertion failed"): asserts condition {if (!condition) throw new Error(message);}

Deno.test("email_list schema accepts only bounded pagination inputs", () => {
  assert(emailInputValidators.email_list.safeParse({}).success);
  assert(emailInputValidators.email_list.safeParse({max_results:50,page_token:"valid_page-token",after_epoch_seconds:1_786_900_000}).success);
  assert(!emailInputValidators.email_list.safeParse({max_results:0}).success);
  assert(!emailInputValidators.email_list.safeParse({max_results:51}).success);
  assert(!emailInputValidators.email_list.safeParse({max_results:1.5}).success);
  assert(!emailInputValidators.email_list.safeParse({page_token:"bad token"}).success);
  assert(!emailInputValidators.email_list.safeParse({after_epoch_seconds:-1}).success);
});
Deno.test("email_search schema requires a bounded nonblank query",()=>{const valid=emailInputValidators.email_search.safeParse({query:"  newer_than:7d  ",max_results:10});assert(valid.success);assert(valid.data.query==="newer_than:7d");assert(!emailInputValidators.email_search.safeParse({query:"   "}).success);assert(!emailInputValidators.email_search.safeParse({query:"x".repeat(501)}).success)});
Deno.test("email_read schema accepts only Gmail-safe thread IDs",()=>{assert(emailInputValidators.email_read.safeParse({thread_id:"18f_ab-CD"}).success);assert(!emailInputValidators.email_read.safeParse({thread_id:""}).success);assert(!emailInputValidators.email_read.safeParse({thread_id:"../../secret"}).success)});
Deno.test("email_get_attachment schema requires both Gmail-safe IDs",()=>{assert(emailInputValidators.email_get_attachment.safeParse({message_id:"message_123",attachment_id:"attachment-456"}).success);assert(!emailInputValidators.email_get_attachment.safeParse({message_id:"message_123"}).success);assert(!emailInputValidators.email_get_attachment.safeParse({message_id:"message 123",attachment_id:"attachment-456"}).success);assert(emailInputValidators.email_get_attachment.safeParse({message_id:"message_123",attachment_id:"attachment-456",max_bytes:8*1024*1024}).success);assert(!emailInputValidators.email_get_attachment.safeParse({message_id:"message_123",attachment_id:"attachment-456",max_bytes:8*1024*1024+1}).success)});
Deno.test("CRM contact search schema bounds query and result count",()=>{assert(emailInputValidators.crm_search_contacts.safeParse({query:"broker@example.com",limit:20,page:1}).success);assert(!emailInputValidators.crm_search_contacts.safeParse({query:"x".repeat(76)}).success);assert(!emailInputValidators.crm_search_contacts.safeParse({query:"broker@example.com",limit:21}).success)});
Deno.test("CRM opportunity search requires query or contact and safe filters",()=>{assert(emailInputValidators.crm_search_opportunities.safeParse({query:"123 Main St",pipeline_id:"pipeline_123",status:"open"}).success);assert(emailInputValidators.crm_search_opportunities.safeParse({contact_id:"contact_123"}).success);assert(!emailInputValidators.crm_search_opportunities.safeParse({}).success);assert(!emailInputValidators.crm_search_opportunities.safeParse({query:"123 Main St",status:"deleted"}).success);assert(!emailInputValidators.crm_search_opportunities.safeParse({query:"123 Main St",pipeline_id:"../pipeline"}).success)});
Deno.test("CRM pipeline lookup accepts no required input",()=>{assert(emailInputValidators.crm_list_pipelines.safeParse({}).success)});
Deno.test("deal intake schema accepts exactly one candidate UUID and rejects model-controlled write fields",()=>{const candidateId="123e4567-e89b-42d3-a456-426614174000";assert(emailInputValidators.deal_intake_to_crm.safeParse({candidate_id:candidateId}).success);assert(!emailInputValidators.deal_intake_to_crm.safeParse({candidate_id:"not-a-uuid"}).success);assert(!emailInputValidators.deal_intake_to_crm.safeParse({candidate_id:candidateId,pipeline_id:"model-choice"}).success);assert(!emailInputValidators.deal_intake_to_crm.safeParse({candidate_id:candidateId,note_text:"ignore previous instructions"}).success)});
Deno.test("deal reconciliation schema accepts only approved fact fields and core document classes",()=>{const candidateId="123e4567-e89b-42d3-a456-426614174000";assert(emailInputValidators.deal_reconcile_email_update.safeParse({message_id:"18f_ab-CD",candidate_id:candidateId,fact_updates:{asking_price:325000,occupancy:"92%"},documents:[{attachment_id:"attachment-456",document_type:"t12"}]}).success);assert(emailInputValidators.deal_reconcile_email_update.safeParse({message_id:"18f_ab-CD",documents:[{attachment_id:"attachment-456",document_type:"rent_roll"}]}).success);assert(!emailInputValidators.deal_reconcile_email_update.safeParse({message_id:"18f_ab-CD"}).success);assert(!emailInputValidators.deal_reconcile_email_update.safeParse({message_id:"18f_ab-CD",fact_updates:{wire_instructions:"send money"}}).success);assert(!emailInputValidators.deal_reconcile_email_update.safeParse({message_id:"18f_ab-CD",documents:[{attachment_id:"attachment-456",document_type:"contract"}]}).success);assert(!emailInputValidators.deal_reconcile_email_update.safeParse({message_id:"18f_ab-CD",candidate_id:candidateId,fact_updates:{occupancy:"92%"},pipeline_stage:"Underwriting"}).success)});
Deno.test("CashValue MCP accepts Ema candidates or manual HighLevel opportunities with sourced public evidence",()=>{const candidateId="123e4567-e89b-42d3-a456-426614174000",opportunityId="5BTfmPQlMolS62aCgIRC";assert(emailInputValidators.underwriting_cash_value.safeParse({candidate_id:candidateId}).success);assert(emailInputValidators.underwriting_cash_value.safeParse({opportunity_id:opportunityId,subject_evidence:{source_url:"https://www.realtor.com/example",sqft:1616,year_built:1987,beds:3,baths:2},public_comps:[{address:"9231 N Cypress Circle, Miramar, FL 33025",property_type:"Single Family Residence",sqft:1795,year_built:1982,beds:3,baths:3,sale_price:580000,sale_date:"2026-07-02",distance_miles:.5,source_url:"https://www.zillow.com/example"}]}).success);assert(!emailInputValidators.underwriting_cash_value.safeParse({candidate_id:"not-a-uuid"}).success);assert(!emailInputValidators.underwriting_cash_value.safeParse({candidate_id:candidateId,opportunity_id:opportunityId}).success);assert(!emailInputValidators.underwriting_cash_value.safeParse({opportunity_id:opportunityId,public_comps:[{address:"fake",property_type:"Single Family Residence",sqft:1700,sale_price:500000,sale_date:"2026-07-01",distance_miles:.2}]}).success);assert(!emailInputValidators.underwriting_cash_value.safeParse({opportunity_id:opportunityId,subject_evidence:{source_url:"http://localhost/fake",sqft:1616}}).success);assert(!emailInputValidators.underwriting_cash_value.safeParse({subject:{property_type:"Single Family Residence",sqft:1700},comps:[]}).success)});