import { z } from "npm:zod@3.25.76";

const gmailId=z.string().min(1).max(512).regex(/^[A-Za-z0-9_-]+$/),pageToken=z.string().min(1).max(2048).regex(/^[A-Za-z0-9_-]+$/).optional(),maxResults=z.number().int().min(1).max(50).optional(),ghlId=z.string().min(1).max(128).regex(/^[A-Za-z0-9_-]+$/),candidateId=z.string().uuid();
const reconcileFactValue=z.union([z.string().trim().min(1).max(1000),z.number().finite(),z.boolean()]);
const reconcileFactUpdates=z.object({property_type:reconcileFactValue.optional(),units:reconcileFactValue.optional(),sites:reconcileFactValue.optional(),pads:reconcileFactValue.optional(),bedrooms:reconcileFactValue.optional(),bathrooms:reconcileFactValue.optional(),sqft:reconcileFactValue.optional(),asking_price:reconcileFactValue.optional(),arv:reconcileFactValue.optional(),repair_estimate:reconcileFactValue.optional(),occupancy:reconcileFactValue.optional(),tenant_rent_monthly:reconcileFactValue.optional(),condition:reconcileFactValue.optional(),renovation_level:reconcileFactValue.optional(),hoa:reconcileFactValue.optional(),post_possession:reconcileFactValue.optional(),fire_damage:reconcileFactValue.optional(),structural_issues:reconcileFactValue.optional(),flood_zone:reconcileFactValue.optional()}).strict();
const intakeFactValue=z.union([reconcileFactValue,z.null()]);
const intakeFacts=z.object({property_type:intakeFactValue.optional(),asset_class:intakeFactValue.optional(),units:intakeFactValue.optional(),sites:intakeFactValue.optional(),pads:intakeFactValue.optional(),bedrooms:intakeFactValue.optional(),bathrooms:intakeFactValue.optional(),sqft:intakeFactValue.optional(),asking_price:intakeFactValue.optional(),arv:intakeFactValue.optional(),repair_estimate:intakeFactValue.optional(),occupancy:intakeFactValue.optional(),tenant_rent_monthly:intakeFactValue.optional(),condition:intakeFactValue.optional(),renovation_level:intakeFactValue.optional(),hoa:intakeFactValue.optional(),hoa_amount:intakeFactValue.optional(),hoa_frequency:intakeFactValue.optional(),hoa_restrictions:intakeFactValue.optional(),post_possession:intakeFactValue.optional(),fire_damage:intakeFactValue.optional(),structural_issues:intakeFactValue.optional(),flood_zone:intakeFactValue.optional(),city:intakeFactValue.optional(),state:intakeFactValue.optional(),zip:intakeFactValue.optional(),county:intakeFactValue.optional(),year_built:intakeFactValue.optional(),lot_size_sqft:intakeFactValue.optional(),listed_with_realtor:intakeFactValue.optional(),listing_status:intakeFactValue.optional(),motivation:intakeFactValue.optional(),timeline:intakeFactValue.optional(),mortgage_status:intakeFactValue.optional(),mortgage_balance:intakeFactValue.optional(),piti:intakeFactValue.optional(),arrears:intakeFactValue.optional(),photos_zillow:intakeFactValue.optional(),zillow_url:intakeFactValue.optional(),deal_room_url:intakeFactValue.optional(),sender_phone:intakeFactValue.optional(),sender_company:intakeFactValue.optional(),flood_and_utilities_info:intakeFactValue.optional()}).strict();
const intakeEvidence=z.object({email:z.array(z.string().trim().min(1).max(2000)).max(20).optional(),attachment:z.array(z.string().trim().min(1).max(2000)).max(20).optional(),source_conflict:z.record(z.string().trim().min(1).max(2000)).optional()}).strict();
const intakeCandidate=z.object({candidate_type:z.string().trim().min(1).max(120).optional(),normalized_address:z.string().trim().min(1).max(300).optional(),extracted_facts:intakeFacts.optional(),evidence:intakeEvidence.optional(),missing_information:z.array(z.string().trim().min(1).max(500)).max(30).optional(),source_type:z.enum(["email","attachment","mixed"]).optional(),intake_result:z.enum(["supported","excluded","needs_classification","needs_info"]).optional()}).strict();
const reconcileDocument=z.object({attachment_id:gmailId,document_type:z.enum(["om","rent_roll","t12","pnl"])}).strict();
const publicSourceUrl=z.string().trim().min(8).max(1000).url().refine(value=>{try{const url=new URL(value),host=url.hostname.toLowerCase();return url.protocol==="https:"&&host.includes(".")&&host!=="localhost"&&!host.endsWith(".local")&&!/^\[?[0-9a-f:.]+\]?$/i.test(host)}catch{return false}},{message:"must be a public HTTPS URL"});
const optionalPropertyFacts={sqft:z.number().finite().min(1).max(50000).optional(),year_built:z.number().finite().min(1600).max(2200).optional(),beds:z.number().finite().min(0).max(50).optional(),baths:z.number().finite().min(0).max(50).optional(),stories:z.number().finite().min(0).max(20).optional(),build_style:z.string().trim().min(1).max(120).optional()};
const publicSubjectEvidence=z.object({source_url:publicSourceUrl,source_name:z.string().trim().min(1).max(120).optional(),...optionalPropertyFacts}).strict().refine(v=>v.sqft!==undefined||v.year_built!==undefined||v.beds!==undefined||v.baths!==undefined||v.stories!==undefined||v.build_style!==undefined,{message:"at least one property fact is required"});
const publicCompEvidence=z.object({id:z.string().trim().min(1).max(128).optional(),address:z.string().trim().min(1).max(300),property_type:z.string().trim().min(1).max(120),sqft:z.number().finite().min(1).max(50000),year_built:z.number().finite().min(1600).max(2200).optional(),beds:z.number().finite().min(0).max(50).optional(),baths:z.number().finite().min(0).max(50).optional(),stories:z.number().finite().min(0).max(20).optional(),build_style:z.string().trim().min(1).max(120).optional(),condition:z.string().trim().min(1).max(120).optional(),sale_price:z.number().finite().positive().max(1_000_000_000),sale_date:z.string().trim().min(10).max(32),distance_miles:z.number().finite().min(0).max(100),source_url:publicSourceUrl,source_name:z.string().trim().min(1).max(120).optional()}).strict().refine(v=>!Number.isNaN(new Date(v.sale_date).getTime()),{message:"sale_date must be valid"});
const rehabScopeItem=z.object({
  category:z.enum(["kitchen","bathrooms","flooring","paint","roof","hvac","electrical","plumbing","windows_doors","landscaping","permits","misc"]),
  scope_level:z.enum(["light","medium","heavy","replace"]),
  description:z.string().trim().min(1).max(500),
  evidence_class:z.enum(["verified","observed","source_claim"]),
  source_type:z.enum(["ghl_field","email","attachment","inspection","photo","contractor_quote","human_verified"]),
  source_ref:z.string().trim().min(1).max(1000),
  quantity:z.number().finite().positive().max(1_000_000).optional(),
}).strict();

export const emailListInputSchema={max_results:maxResults,page_token:pageToken,after_epoch_seconds:z.number().int().min(0).max(Number.MAX_SAFE_INTEGER).optional()};
export const emailSearchInputSchema={query:z.string().trim().min(1).max(500),max_results:maxResults,page_token:pageToken};
export const emailReadInputSchema={thread_id:gmailId};
export const emailGetAttachmentInputSchema={message_id:gmailId,attachment_id:gmailId,max_bytes:z.number().int().min(64*1024).max(8*1024*1024).optional()};
export const crmSearchContactsInputSchema={query:z.string().trim().min(1).max(75),limit:z.number().int().min(1).max(20).optional(),page:z.number().int().min(1).max(1000).optional()};
export const crmSearchOpportunitiesInputSchema={query:z.string().trim().min(1).max(200).optional(),contact_id:ghlId.optional(),pipeline_id:ghlId.optional(),stage_id:ghlId.optional(),status:z.enum(["open","won","lost","abandoned","all"]).optional(),limit:z.number().int().min(1).max(50).optional(),page:z.number().int().min(1).max(1000).optional()};
export const crmListPipelinesInputSchema={};
export const dealPersistEmailIntakeInputSchema={message_id:gmailId,message_disposition:z.enum(["deal","excluded"]),exclusion_reason:z.string().trim().min(1).max(500).optional(),candidates:z.array(intakeCandidate).max(20).optional()};
export const dealBuyBoxFitInputSchema={candidate_id:candidateId};
export const dealIntakeToCrmInputSchema={candidate_id:candidateId};
export const dealReconcileEmailUpdateInputSchema={message_id:gmailId,candidate_id:candidateId.optional(),fact_updates:reconcileFactUpdates.optional(),documents:z.array(reconcileDocument).max(8).optional()};
export const underwritingNextWorkItemInputSchema={};
export const underwritingCashValueInputSchema={candidate_id:candidateId.optional(),opportunity_id:ghlId.optional(),subject_evidence:publicSubjectEvidence.optional(),public_comps:z.array(publicCompEvidence).max(25).optional()};
export const underwritingRehabInputSchema={opportunity_id:ghlId,scope_items:z.array(rehabScopeItem).min(1).max(50)};

const dealPersistEmailIntakeValidator=z.object(dealPersistEmailIntakeInputSchema).strict().superRefine((v,ctx)=>{const count=v.candidates?.length??0;if(v.message_disposition==="deal"&&count===0)ctx.addIssue({code:z.ZodIssueCode.custom,message:"deal messages require at least one candidate"});if(v.message_disposition==="excluded"&&count>0)ctx.addIssue({code:z.ZodIssueCode.custom,message:"excluded messages cannot include candidates"})});
const dealReconcileValidator=z.object(dealReconcileEmailUpdateInputSchema).strict().refine(v=>Boolean(v.fact_updates&&Object.keys(v.fact_updates).length)||Boolean(v.documents?.length),{message:"fact_updates or documents is required"});
const underwritingCashValueValidator=z.object(underwritingCashValueInputSchema).strict().refine(v=>Number(Boolean(v.candidate_id))+Number(Boolean(v.opportunity_id))===1,{message:"exactly one of candidate_id or opportunity_id is required"});
export const emailInputValidators={email_list:z.object(emailListInputSchema),email_search:z.object(emailSearchInputSchema),email_read:z.object(emailReadInputSchema),email_get_attachment:z.object(emailGetAttachmentInputSchema),crm_search_contacts:z.object(crmSearchContactsInputSchema),crm_search_opportunities:z.object(crmSearchOpportunitiesInputSchema).refine(v=>Boolean(v.query||v.contact_id),{message:"query or contact_id is required"}),crm_list_pipelines:z.object(crmListPipelinesInputSchema),deal_persist_email_intake:dealPersistEmailIntakeValidator,deal_buy_box_fit:z.object(dealBuyBoxFitInputSchema).strict(),deal_intake_to_crm:z.object(dealIntakeToCrmInputSchema).strict(),deal_reconcile_email_update:dealReconcileValidator,underwriting_next_work_item:z.object(underwritingNextWorkItemInputSchema).strict(),underwriting_cash_value:underwritingCashValueValidator,underwriting_rehab:z.object(underwritingRehabInputSchema).strict()} as const;
